version: '3'

networks:
    forontend:
    backend:

services:
    php-fpm:
        build:
            context: ./php-fpm
            args:
                - VERSION=7.4
        volumes:
            - ~/www:/var/www
        expose:
            - "9000"
        networks:
            - backend

    mariadb:
        build:
            context: ./mariadb
            args:
                - VERSION=10
        volumes:
            - ~/.lnmp/mariadb-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "3306:3306"
        networks:
            - backend

    nginx:
        build:
            context: ./nginx
            args:
                - VERSION=1.11
        volumes:
            - ~/www:/var/www
        ports:
            - "80:80"
            - "81:81"
            - "443:443"
        depends_on:
            - php-fpm
        networks:
            - backend