version: '3'

networks:
    forontend: 
    backend: 

services:
    php-fpm:
        build:
            context: ${PHPFPM_BUILD_PATH}
            args:
                - PHPFPM_VERSION=${PHPFPM_VERSION}
                - PHPFPM_HOST_NAME=${PHPFPM_HOST_NAME}
                - PHPFPM_HOST_PORT=${PHPFPM_HOST_PORT}
        volumes:
            - ${PROJECT_PATH}:/var/www
        networks:
            - backend

    mariadb:
        build:
            context: ${MARIADB_BUILD_PATH}
            args:
                - MARIADB_VERSION=${MARIADB_VERSION}
                - MARIADB_HOST_NAME=${MARIADB_HOST_NAME}
                - MARIADB_HOST_PORT=${MARIADB_HOST_PORT}
        volumes:
            - ${DATA_PATH}:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        networks:
            - backend

    nginx:
        build:
            context: ${NGINX_BUILD_PATH}
            args:
                - NGINX_VERSION=${NGINX_VERSION}
                - NGINX_HOST_NAME=${NGINX_HOST_NAME}
                - NGINX_HOST_HTTP_PORT=${NGINX_HOST_HTTP_PORT}
                - NGINX_HOST_HTTPS_PORT=${NGINX_HOST_HTTPS_PORT}
        volumes:
            - ${PROJECT_PATH}:/var/www
            - ${NGINX_SITES_PATH}:/etc/nginx/sites
            - ${NGINX_CONFD_PATH}:/etc/nginx/conf.d
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        depends_on:
            - ${PHPFPM_HOST_NAME}
        networks:
            - backend