version: '3'

networks:
    frontend: 
    backend: 

services:

    php-fpm:
        container_name: lnmp.php-fpm
        build:
            context: ${PHPFPM_BUILD_PATH}
            args:
                - PHPFPM_VERSION=${PHPFPM_VERSION}
        volumes:
            - ${PROJECT_PATH}:/var/www
        expose:
            - ${PHPFPM_EXPOSE}
        networks:
            - backend

    nginx:
        container_name: lnmp.nginx
        build:
            context: ${NGINX_BUILD_PATH}
            args:
                - NGINX_VERSION=${NGINX_VERSION}
                - NGINX_CONN_PHPFPM=${NGINX_CONN_PHPFPM}
                - NGINX_CONN_PHPFPM_PORT=${NGINX_CONN_PHPFPM_PORT}
        volumes:
            - ${PROJECT_PATH}:/var/www
            - ${NGINX_SITES_PATH}:/etc/nginx/sites
        expose:
            - ${NGINX_HTTP_EXPOSE}
            - ${NGINX_HTTPS_EXPOSE}
        ports:
            - "${NGINX_HTTP_PORT}:${NGINX_HTTP_EXPOSE}"
            - "${NGINX_HTTPS_PORT}:${NGINX_HTTPS_EXPOSE}"
        networks:
            - backend
        depends_on:
            - ${NGINX_CONN_PHPFPM}

    mariadb:
        container_name: lnmp.mariadb
        build:
            context: ${MARIADB_BUILD_PATH}
            args:
                - MARIADB_VERSION=${MARIADB_VERSION}
        environment:
            - MYSQL_DATABASE=${MARIADB_DATABASE}
            - MYSQL_USER=${MARIADB_USER}
            - MYSQL_PASSWORD=${MARIADB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        volumes:
            - ${DATA_PATH}:/var/lib/mysql
        expose:
            - ${MARIADB_EXPOSE}
        networks:
            - backend

    phpmyadmin:
        container_name: lnmp.phpmyadmin
        build: 
            context: ${PMA_BUILD_PATH}
            args:
                - PMA_VERSION=${PMA_VERSION}
        environment:
            # - UPLOAD_LIMIT=
            - PMA_ARBITRARY=1
            - PMA_HOST=${PMA_CONN_DB}
            - PMA_PORT=${MARIADB_EXPOSE}
            - MYSQL_USER=${MARIADB_USER}
            - MYSQL_PASSWORD=${MARIADB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        expose:
            - ${PMA_EXPOSE}
        ports:
            - "${PMA_HTTP_PORT}:${PMA_EXPOSE}"
        networks:
            - frontend
            - backend
        depends_on:
            - ${PMA_CONN_DB}
